### ISSUE TITLE
Provide license for your script

### ISSUE THREAD

**Issue by kepi** [Herjar/radarr_sonarr_watchmon#12]
Hello,

I would like to use modify your script to suit my needs, but there is no license specified and I'm not sure about permitted uses, attribution etc.

If possible, please add license for your code, following link can help you with that:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks

**Comment by Herjar** [comment]
A license has been added now. 

Sorry for the very late reply.
