### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by gitthangbaby** [Herjar/radarr_sonarr_watchmon#14]
Report exit codes 1, 2, 3 based on error.
or at least
Report exit code higher than 0 for any error.

Otherwise there's no way to know there was an error.
Thanks!

**Comment by Herjar** [comment]
I am using a string with sys.exit(), which should be interpreted as an error I think?
There was one error missing a string (if the auth was out of date), but that should be fixed now.

Just let me know if it still does not work as expected.
