### ISSUE TITLE
Updated to sonarr 4.0.0.317-ls366 by linuxserver.io

### ISSUE THREAD

**Issue by olvier** [Herjar/radarr_sonarr_watchmon#15]
Is there any adjustment needed, with new version of sonarr?

<img width="693" alt="image" src="https://user-images.githubusercontent.com/13106409/210272160-b1ab57d4-fd9f-4f75-bb65-360f289b84ef.png">

**Comment by fadiajlil** [comment]
Try to change the `http://"+self.sonarr_address+"/api/tag?apikey="+self.sonarr_apikey` to `http://"+self.sonarr_address+"/api/v3/tag?apikey="+self.sonarr_apikey`
change all the one with /api/ to /api/v3 in the sonarr config
that's what worked for me

**Comment by Herjar** [comment]
Fixed in #[04cf47d](https://github.com/Herjar/radarr_sonarr_watchmon/commit/04cf47da4ce5fa9bd193a9e4268847dfdcd4a66e)

**Comment by olvier** [comment]
thank you!! love ya all!
