### ISSUE TITLE
Add error message for if the Sonarr (or other) API key isn't working?

### ISSUE THREAD

**Issue by somegirl** [Herjar/radarr_sonarr_watchmon#5]
Hi there, just a thought, if it's possible, you might consider adding some kind of error message if the Sonarr (or other) API key isn't working. I noticed the script hadn't been working lately and was trying to figure out why - updated, re-authenticated with Trakt - before thinking to check my Sonarr API key. (I built a new PC recently, re-installing Sonarr along the way, but I hadn't thought to update the API key in my saved-from-before config.yml.)

The way it expressed itself was for the script to end with "Sonarr: Episodes found and changed monitored to False:" and then none were listed. Perhaps it might be possible to report back that the API key failed?

At any rate, thanks for sharing this script! Let me know if you have any PayPal, Venmo, etc. to accept donations!

**Comment by Herjar** [comment]
Hi. I have updated to check for unauthorised requests to the APIs. Please check if it works as expected.

Don't worry about donations. I have a job :)

**Comment by somegirl** [comment]
Awesome! I tested with a bad API key and my actual API key and it worked as expected! (I.e., gave the error/prompt with the bad API key and worked fine/normal with the good key!)
