### ISSUE TITLE
[FEATURE_REQUEST] add tag instead of un-monitoring

### ISSUE THREAD

**Issue by olvier** [Herjar/radarr_sonarr_watchmon#6]
Hey, do you think its possible to add an "watched"-tag instead of un-monitoring watched movies?

Would be great, because i am still holding most watched movies.
And of they where good enough, i am also willing for an upgrade. 
Or otherwise, if i am running out of space, i could display all watched movies and could delete the worst by hand.

**Comment by Herjar** [comment]
Hi. I have added support for adding tags in Radarr and Sonarr now. If you do not want to unmonitor as well just set `unmonitor: False` under the app in the config. Sonarr can only tag shows, not episodes. Not sure how useful that is, but it is supported at least.

**Comment by olvier** [comment]
![image](https://user-images.githubusercontent.com/13106409/123869694-9ae11800-d931-11eb-98af-c8dd33d67601.png)

Any idea, whats wrong here?
First i thought, its because of radarr v4, but sonarr v3 is quite "old" and results in the same error.

But for now: thanks for adding tag-support, i will love it, if i get this to run.

**Comment by Herjar** [comment]
My authentication was cached so I forgot to check that the auth to trakt works after the new changes :worried:

I pushed a new update now. Could you check if that works for you?

**Comment by olvier** [comment]
Yeah, it works, and it's awesome! Thank you for your time, to code this cool stuff!!!

But one last additional question: How can i run the script once, for **_the whole_** library?
Should i temporarily edit `recent_days: 30` from `config.yml` to `recent_days: 35600`,
for watched movies in the last 100 years?

Or did you expect/recognized sth critical there?


edit: i couldn't wait and tested for myself.
Works like a charm, but only 300 watched movies in 100 years in a library of 1400.

thank you so much!
