### ISSUE TITLE
Use Plex API instead of Trakt?

### ISSUE THREAD

**Issue by karan** [Herjar/radarr_sonarr_watchmon#9]
I just came across this project (great work!). I was wondering why you are using Trakt and not Plex API directly to get watched content: https://python-plexapi.readthedocs.io/en/latest/introduction.html

```
movies = plex.library.section('Movies')
for video in movies.search(unwatched=False):
    print(video.title)
```

**Comment by Herjar** [comment]
The main reason is that not everyone uses Plex. It is easier to just support Trakt than having to support Plex, Emby, Jellyfin, Kodi etc.
